solution: solution.c ../../handy/include/handy_string.c ../../handy/include/handy_hashtbl.c ../../handy/include/handy_list.c
	gcc -o solution ../../handy/include/handy_string.c ../../handy/include/handy_hashtbl.c ../../handy/include/handy_list.c solution.c 
	
	
clean:
	rm *.o
